#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Axel Brando

# Short bio or description (displayed in the header)
shortbio: Computer Scientist and Mathematician
description: Computer Scientist and Mathematician. This is a collection of outstanding projects I have been working in recent years.

# Email Adress
##email:

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/14802914?v=3&s=460 #images/avatar.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  emailpre: axelbrando
  emailpos: ub.edu
  facebook:
  flickr:
  github: axelbrando
  instagram:
  linkedin: AxelBrando
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: AxelBrando_
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: axeldisqus

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-101022346-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://axelbrando.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

author:
  workHistory:

    - work0:
      company: Universitat de Barcelona (UB) - BBVA AI Factory
      location: Barcelona
      title: Industrial PhD Disseration Defense
      started: 2022
      duration: Mon 18th of July, 2022
      description: <p>Today, I am glad to announce I will be defending my Industrial PhD Dissertation.</p>![Cover]({{ site.baseurl }}/images/PhDDefenseCover.png)<p></p><p>Abstract: Uncertainty is always around us. Every decision we take has an associated likelihood of success and decisions made by autonomous systems are not an exception. Despite the great advances in the field of artificial intelligence, the inability of these systems to identify a higher risk scenario a priori could prevent their inclusion as part of solutions to many real problems. This is why it is essential that these systems learn how to model and deal with uncertainty. Starting from a probabilistic approach, this thesis proposes to formalize the different types of uncertainty and, in particular, focus its research on one type of uncertainty, the aleatoric uncertainty, since it is detected as the main uncertainty for the financial real-world problem that motivates this doctorate. Based on such research, the thesis proposes new models to improve the state of the art in modeling such uncertainty as well as introduces a new real problem that appears when there is a fixed predictive system that does not model uncertainty and we want to model uncertainty a posteriori, without changing the original model. This problem will be denoted as the modeling of the uncertainty of a black box system and will motivate the proposal of new models specialized in maintaining the predictive advantages, such as Quantile Regression (QR), but for the black box problem. Subsequently, the QR research will motivate the proposal of new models to solve a QR literature problem known as the crossing quantile phenomena, which appears when different quantiles are predicted simultaneously and they do not preserve their correct order with respect to their quantile value. Finally, all of the above research will be summarized in visualization and evaluation methods for the predicted uncertainty to produce uncertainty-tailored methods.</p><p></p><p></p><p></p>A first copy of the dissertation can be found here: <a href="https://drive.google.com/uc?export=download&id=1pVOkLg18d7pj9rKbtGESYbtADyT2U0VV">BrandoAxel_AleatoricUncertainty.pdf</a></p><p></p><p></p><p>Soon, we will: (1) Add the formal information to reference its content. (2) Update this blog for a web version of the PhD dissertation. (3) Publish new related results. </p><p>Stay tuned via social networks!</p><p>Thank you all.</p><p>Best Regards</p>

    - work1:
      company: Barcelona Supercomputing Center (BSC)
      location: Barcelona
      title: Research Engineer (RE2)
      started: 2020
      duration: (2020-present)
      description: <p>Research and risk analysis for safety-critical real-time systems based on Machine Learning techniques.</p>

    - work2:
      company: BBVA Data & Analytics S.L. - Universitat de Barcelona (UB)
      location: Barcelona
      title: Data Scientist Industrial PhD student
      started: 2017
      duration: (2017-present)
      description: <p> Research about Uncertainty Modelling by using Deep Learning motivated by the bank problems. </p><p>...</p><p>2020-06-04 -- Journal article about <a href="https://ieeexplore.ieee.org/document/9131769">Building uncertainty models on top of black-box predictive APIs</a>.</p><p>2019-12-11 -- NeurIPS'19 presentation of the article 'Modelling heterogeneous distributions with an Uncountable Mixture of Asymmetric Laplacians' (UMAL). <a href="https://arxiv.org/abs/1910.12288">Article</a>, <a href="https://github.com/BBVA/UMAL">Code repo</a>, <a href="https://vimeo.com/369179175/a17d3de911">Video</a>. Introduced <a href="https://www.bbva.com/es/como-ensenar-a-la-inteligencia-artificial-a-decir-no-estoy-seguro/">here</a> and <a href="https://retina.elpais.com/retina/2019/12/20/innovacion/1576838697_328758.html?ssm=TW_CC">here</a>.</p></p><p>2019-10-01 -- Fall'19 BCN.ai.  <a href="https://w.tame.events/e/89635027"> Presentation about Aleatoric Uncertainty Modelling by using UMAL</a>.</p><p></p><p>2018-09-10 -- Regarding the aggregated time-series financial forecasting system the article entitled <a href="http://arxiv.org/abs/1807.09011">'Uncertainty Modelling in Deep Networks Forecasting; Short and Noisy Series'</a> was presented at the Applied Data Science Track of ECML-PKDD 2018 and <a href="https://www.bbvadata.com/es/improving-predictions-in-deep-learning-by-modelling-uncertainty-2/">here</a>. The proposed model was afterwards used in the <a href="https://www.bbvadata.com/white_papers/advanced_ai.pdf">White Paper (collaboration between Google Cloud - BBVA Data Analytics)</a> and introduced <a href="https://www.bbvadata.com/es/bayesian-deep-learning-meets-google-cloud-for-a-better-forecasting-engine-at-bbva/">here</a> and <a href="https://www.bbva.com/es/bbva-y-google-cloud-desarrollan-un-modelo-de-ia-para-mejorar-la-prediccion-de-gastos-e-ingresos/">here</a>.</p><p></p><p>2018-05-13 -- First BCN.ai session, presenting <a href="https://w.tame.events/e/3177403">how to model all kinds of uncertainties by using a Deep Learning model</a>.</p><p></p><p>2018-03-14 -- BGSMath Presentation about <a href="http://doctoratsindustrials.gencat.cat/ca/events/view/108">Large-scale machine learning for financial recommender systems</a>.</p><p></p>

    - work3:
      company: IIIA - CSIC (Artificial Intelligence Research Institute)
      location: Bellaterra
      title: Big Data / Machine Learning research developer
      started: 2017
      duration: (2017)
      description: <p> Research developer in a industrial research project.</p>

    - work4:
      company: Universitat de Barcelona (UB)
      location: Barcelona
      title: Scholarship collaboration AAD with the department of Applied Mathematics and Analysis
      started: 2016
      duration: (2016)
      description: <p> Collaborating in support tasks with the university teachers.</p>

    - work5:
      company: DataScienceUB group, Universitat de Barcelona (UB)
      location: Barcelona
      title: Course assistant in the <a href="http://www.ub.edu/datascience/deep/">Deep Learning from Scratch:</a> A short Course
      started: 2016
      duration: (2016)
      description: <p> Content review. </p><p>Teacher assistant during sessions.</p><p>Preparation and explanation of the theoretical and practical content of style transfer of images by using neural networks.</p>

    - work6:
      company: Universitat de Barcelona (UB)
      location: Barcelona
      title: Scholarship collaboration with the department of Applied Mathematics and Analysis
      started: 2015
      duration: (2015-2016)
      description: <p> Design and experimentation in new databases. </p><p>Building of new models of deep learning by using Caffe and TensorFlow.</p><p>Introducing to new techniques such as Style Transfer Image, Hallucinations, Dreaming by using deep learning algorithms.</p>

    - work7:
      company: Barcelona Super-Computing Center (BSC)
      location: Barcelona
      title: Research and experimental development on deep learning techniques
      started: 2015
      duration: (2015-2016)
      description: <p>Techniques to reconstruct the input by using the activations of the neural network. </p>

    - work8:
      company: Universitat de Barcelona (UB)
      location: Barcelona
      title: Building and training artificial deep learning techniques by using Caffe
      started: 2015
      duration: (2015)
      description: <p>Building a new model of deep learning improving the results obtained in my final degree dissertation.</p>

  educationHistory:
    - education1:
      organization: Universitat de Barcelona (UB), Universitat Polit√®cnica de Catalunya (UPC), Universitat Rovira i Virgili (URV).
      degree: Master's Degree
      major: Artificial Intelligence
      started: 2017
      duration: (2015 - 2017)
      description: Master in Artificial Intelligence
    - education2:
      organization: Universitat de Barcelona (UB)
      degree: Bachelor's Degree
      major: Computer Engineering
      started: 2015
      duration: (2009 - 2015)
      description: Dual EHEA Bachelor's Degree in Mathematics and Computer Engineering
    - education3:
      organization: Universitat de Barcelona (UB)
      degree: Bachelor's Degree
      major: Mathematics
      started: 2015
      duration: (2009 - 2015)
      description: Dual EHEA Bachelor's Degree in Mathematics and Computer Engineering
